-- Archivo creado  - domingo-agosto-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOX
--------------------------------------------------------

  CREATE TABLE "ROULETTE"."BOX" 
   (	"ID_BOX" NUMBER, 
	"NUMBER_BOX" NUMBER, 
	"COLOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROULETTE.BOX
SET DEFINE OFF;
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('1','1','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('2','2','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('3','3','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('4','4','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('5','5','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('6','6','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('7','7','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('8','8','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('9','9','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('10','10','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('11','11','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('12','12','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('13','13','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('14','14','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('15','15','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('16','16','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('17','17','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('18','18','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('19','19','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('20','20','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('21','21','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('22','22','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('23','23','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('24','24','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('25','25','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('26','26','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('27','27','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('28','28','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('29','29','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('30','30','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('31','31','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('32','32','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('33','33','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('34','34','ROJO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('35','35','NEGRO');
Insert into ROULETTE.BOX (ID_BOX,NUMBER_BOX,COLOR) values ('36','36','ROJO');
--------------------------------------------------------
--  DDL for Index ROULETTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROULETTE"."ROULETTE_PK" ON "ROULETTE"."BOX" ("ID_BOX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOX
--------------------------------------------------------

  ALTER TABLE "ROULETTE"."BOX" ADD CONSTRAINT "ROULETTE_PK" PRIMARY KEY ("ID_BOX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROULETTE"."BOX" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "ROULETTE"."BOX" MODIFY ("NUMBER_BOX" NOT NULL ENABLE);
  ALTER TABLE "ROULETTE"."BOX" MODIFY ("ID_BOX" NOT NULL ENABLE);
